/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IChefIncentivesLite } from "./IChefIncentivesLite";

export class IChefIncentivesLiteFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChefIncentivesLite {
    return new Contract(address, _abi, signerOrProvider) as IChefIncentivesLite;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "poolInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "totalSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastRewardTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "accKlapPerShare",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "accKlapPerFactorShare",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sumOfFactors",
        type: "uint256",
      },
      {
        internalType: "contract IOnwardIncentivesController",
        name: "onwardIncentives",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
