/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IMasterChefInterface extends ethers.utils.Interface {
  functions: {
    "depositFromVe(address,uint256,address)": FunctionFragment;
    "updateFactor(address)": FunctionFragment;
    "withdrawFromVe(address,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "depositFromVe",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFactor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromVe",
    values: [string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositFromVe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromVe",
    data: BytesLike
  ): Result;

  events: {};
}

export class IMasterChef extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IMasterChefInterface;

  functions: {
    depositFromVe(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "depositFromVe(address,uint256,address)"(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    updateFactor(
      _user: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateFactor(address)"(
      _user: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawFromVe(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawFromVe(address,uint256,address)"(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  depositFromVe(
    _token: string,
    _amount: BigNumberish,
    _user: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "depositFromVe(address,uint256,address)"(
    _token: string,
    _amount: BigNumberish,
    _user: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  updateFactor(
    _user: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateFactor(address)"(
    _user: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawFromVe(
    _token: string,
    _amount: BigNumberish,
    _user: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawFromVe(address,uint256,address)"(
    _token: string,
    _amount: BigNumberish,
    _user: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    depositFromVe(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "depositFromVe(address,uint256,address)"(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFactor(_user: string, overrides?: CallOverrides): Promise<void>;

    "updateFactor(address)"(
      _user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFromVe(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawFromVe(address,uint256,address)"(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    depositFromVe(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "depositFromVe(address,uint256,address)"(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    updateFactor(_user: string, overrides?: Overrides): Promise<BigNumber>;

    "updateFactor(address)"(
      _user: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawFromVe(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawFromVe(address,uint256,address)"(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositFromVe(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "depositFromVe(address,uint256,address)"(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    updateFactor(
      _user: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateFactor(address)"(
      _user: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawFromVe(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawFromVe(address,uint256,address)"(
      _token: string,
      _amount: BigNumberish,
      _user: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
