/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IOnwardIncentivesControllerInterface extends ethers.utils.Interface {
  functions: {
    "handleAction(address,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "handleAction",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "handleAction",
    data: BytesLike
  ): Result;

  events: {};
}

export class IOnwardIncentivesController extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IOnwardIncentivesControllerInterface;

  functions: {
    handleAction(
      _token: string,
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "handleAction(address,address,uint256,uint256)"(
      _token: string,
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  handleAction(
    _token: string,
    _user: string,
    _balance: BigNumberish,
    _totalSupply: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "handleAction(address,address,uint256,uint256)"(
    _token: string,
    _user: string,
    _balance: BigNumberish,
    _totalSupply: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    handleAction(
      _token: string,
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "handleAction(address,address,uint256,uint256)"(
      _token: string,
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    handleAction(
      _token: string,
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "handleAction(address,address,uint256,uint256)"(
      _token: string,
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    handleAction(
      _token: string,
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "handleAction(address,address,uint256,uint256)"(
      _token: string,
      _user: string,
      _balance: BigNumberish,
      _totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
