/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IOnwardIncentivesController } from "./IOnwardIncentivesController";

export class IOnwardIncentivesControllerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOnwardIncentivesController {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IOnwardIncentivesController;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_balance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_totalSupply",
        type: "uint256",
      },
    ],
    name: "handleAction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
